export { default as Navbar } from './Navbar';
export { default as Hero } from './Hero';
export { default as TrustStrip } from './TrustStip';
export { default as DashboardPreview } from './DashboardPreview';
export { default as Features } from './Features';
export { default as HowItWorks } from './HowItWorks';
export { default as Testimonials } from './Testimonials';
export { default as Roadmap } from './Roadmap'
export { default as  FAQ } from './faq';
export { default as CTA } from './cta';
export { default as Footer } from './Footer'